/*
  Create function that normalizes the Rate between Strong/Weak
  currency pairs

  Author: Mohsin
  Date: April 13, 2017

 */


-- Drop Existing Function

DROP FUNCTION f_fixrate(VARCHAR,varchar,float);


-- Create a new User Defined Function

CREATE FUNCTION f_fixrate(fromccy VARCHAR(3), toccy VARCHAR(3), rate FLOAT)
  RETURNS FLOAT
STABLE
  AS $$
     if rate is None or rate == 0.0 or rate == 0:
        return 0.0

     elif fromccy == toccy:
        return 1.0

     elif toccy == "USD":
        if fromccy in ["EUR","GBP","AUD","NZD"]:
           return rate
        return 1/rate

     elif toccy == "EUR":
        return 1/rate

     elif toccy == "CAD":
        if fromccy in ["USD","EUR","AUD","GBP","NZD"]:
          return rate
        return 1/rate

     elif toccy == "GBP":
       if fromccy in ["EUR","BGN"]:
          return rate
       return 1/rate

     elif toccy == "NZD":
       if fromccy in ["EUR","AUD","GBP","CHF","SGD"]:
         return rate
       return 1/rate

     elif toccy == "AUD":
       if  fromccy in ["EUR","GBP"]:
         return rate
       return 1/rate

     elif fromccy + toccy in ["EURUSD","GBPUSD","USDJPY","USDSGD","USDMXN","USDTRY","USDHKD","USDSAR","USDCAD","AUDUSD","USDCHF","NZDUSD","USDZAR","USDCZK","USDDKK","USDHUF","USDINR","USDNOK","USDPLN","USDSEK","USDUSD","USDAED","USDBHD","USDFJD","USDILS","USDJOD","USDKWD","USDMAD","USDOMR","USDPHP","USDQAR","USDXPF","EURAUD","EURBHD","EURCAD","EURCHF","EURCZK","EURDKK","EUREUR","EURFJD","EURGBP","EURHKD","EURHUF","EURILS","EURINR","EURJOD","EURJPY","EURKWD","EURMAD","EURMXN","EURNOK","EURNZD","EUROMR","EURPHP","EURPLN","EURQAR","EURSAR","EURSEK","EURSGD","EURTRY","EURXPF","EURZAR","CADAED","CADBHD","AUDCAD","CADCHF","CADCZK","CADDKK","CADFJD","GBPCAD","CADHKD","CADHUF","CADILS","CADJOD","CADJPY","CADKWD","CADMAD","CADMXN","CADNOK","NZDCAD","CADOMR","CADPHP","CADPLN","CADQAR","CADSAR","CADSEK","CADSGD","CADTRY","CADXPF","CADZAR","CADCAD","USDCNY","USDNGN","USDGTQ","USDTHB","USDRON","CADINR","AUDAED","AUDAUD","AUDBHD","AUDCHF","AUDCZK","AUDDKK","AUDFJD","GBPAUD","AUDHKD","AUDHUF","AUDILS","AUDINR","AUDJOD","AUDJPY","AUDKWD","AUDMAD","AUDMXN","AUDNOK","AUDNZD","AUDOMR","AUDPHP","AUDPLN","AUDQAR","AUDSAR","AUDSEK","AUDSGD","AUDXPF","AUDZAR","AUDRON","GBPAED","GBPBHD","GBPCHF","GBPCZK","GBPDKK","GBPFJD","GBPHKD","GBPHUF","GBPILS","GBPINR","GBPJOD","GBPJPY","GBPKWD","GBPMAD","GBPMXN","GBPNOK","GBPNZD","GBPOMR","GBPPHP","GBPPLN","GBPQAR","GBPSAR","GBPSEK","GBPSGD","GBPTRY","GBPXPF","GBPZAR","USDKRW","USDARS","EURAED","BGNUSD","USDBRL","USDIDR","USDMYR","USDPEN","USDRUB","USDTWD","USDUAH","USDLTL","USDKES","USDHRK","USDTND","USDMUR","USDLVL","EURTHB","GBPTHB","CADTHB","AUDTHB","EURRON","GBPRON","CADRON","EURPEN","GBPPEN","CADPEN","AUDPEN","GBPMUR","EURMUR","AUDMUR","CADMUR","AUDTND","CADTND","EURTND","GBPTND","AUDHRK","CADHRK","EURHRK","GBPHRK","AUDKES","CADKES","EURKES","GBPKES","AUDLTL","CADLTL","EURLTL","GBPLTL","AUDLVL","CADLVL","EURLVL","GBPLVL","AUDMYR","CADMYR","EURMYR","GBPMYR","AUDRUB","CADRUB","EURRUB","GBPRUB","AUDNGN","CADNGN","EURNGN","GBPNGN","AUDUAH","CADUAH","EURUAH","GBPUAH","AUDTWD","CADTWD","EURTWD","AEDZAR","ARSZAR","BGNZAR","BHDZAR","BRLZAR","CHFZAR","FJDZAR","GTQZAR","HKDZAR","HRKZAR","HUFZAR","IDRZAR","ILSZAR","INRZAR","JODZAR","JPYZAR","KESZAR","KRWZAR","KWDZAR","LTLZAR","LVLZAR","MADZAR","MURZAR","MXNZAR","MYRZAR","NGNZAR","NOKZAR","NZDZAR","OMRZAR","PENZAR","PHPZAR","PLNZAR","QARZAR","RONZAR","RUBZAR","SARZAR","SEKZAR","SGDZAR","THBZAR","TNDZAR","TRYZAR","TWDZAR","UAHZAR","XPFZAR","GBPGBP","ZARZAR","EURBGN","BGNGBP","EURCNY","GBPCNY","CADCNY","ZARCNY","AUDCNY","AUDIDR","AUDKRW","EURKRW","GBPKRW","CADKRW","GBPBRL","AUDTRY","AUDBGN","AUDBRL","EURBRL","CADBRL","GBPTWD","JPYAED","JPYARS","JPYBGN","JPYBHD","JPYBRL","JPYCNY","JPYCZK","DKKJPY","JPYFJD","JPYGTQ","JPYHKD","JPYHRK","JPYHUF","JPYIDR","CHFJPY","ILSJPY","JPYXPF","JPYUAH","JPYTWD","TRYJPY","JPYTND","JPYTHB","SGDJPY","SEKJPY","JPYSAR","JPYRUB","JPYRON","JPYQAR","PLNJPY","JPYPHP","JPYPEN","JPYOMR","NZDJPY","NOKJPY","JPYINR","JPYJOD","JPYKES","JPYKRW","JPYKWD","JPYLTL","JPYLVL","JPYMAD","JPYMUR","JPYMYR","MXNJPY","JPYNGN","EURIDR","CADIDR","GBPIDR","EURARS","EURGTQ","CADGTQ","CADARS","CADBGN","AUDGTQ","AUDARS","GBPGTQ","GBPARS","ZARCZK","DKKCZK","JPYJPY","USDVND","CADVND","AUDVND","GBPVND","EURVND","ZARVND","EURGHS","USDGHS","ZARGHS","GBPGHS","AUDGHS","CADGHS","USDCOP","EURCOP","GBPCOP","ZARCOP","AUDCOP","CADCOP","USDPKR","EURPKR","GBPPKR","ZARPKR","AUDPKR","CADPKR","USDLKR","EURLKR","ZARLKR","AUDLKR","CADLKR","GBPLKR","USDBDT","EURBDT","GBPBDT","ZARBDT","AUDBDT","CADBDT","USDNPR","EURNPR","GBPNPR","ZARNPR","AUDNPR","CADNPR","USDKZT","EURKZT","GBPKZT","ZARKZT","AUDKZT","CADKZT","USDJMD","EURJMD","GBPJMD","ZARJMD","AUDJMD","CADJMD","USDEGP","EUREGP","GBPEGP","ZAREGP","AUDEGP","CADEGP","USDUGX","EURUGX","GBPUGX","ZARUGX","AUDUGX","CADUGX","USDCRC","EURCRC","GBPCRC","ZARCRC","AUDCRC","CADCRC","USDVEF","EURVEF","ZARVEF","CADVEF","AUDVEF","GBPVEF","USDMNT","EURMNT","CADMNT","AUDMNT","GBPMNT","ZARMNT","USDCLP","GBPCLP","EURCLP","ZARCLP","AUDCLP","CADCLP","USDDOP","GBPDOP","EURDOP","ZARDOP","AUDDOP","CADDOP","USDHNL","GBPHNL","EURHNL","ZARHNL","AUDHNL","CADHNL","USDXAF","GBPXAF","EURXAF","ZARXAF","AUDXAF","CADXAF","USDBBD","GBPBBD","EURBBD","ZARBBD","AUDBBD","CADBBD","USDGEL","GBPGEL","EURGEL","ZARGEL","AUDGEL","CADGEL","USDUYU","GBPUYU","EURUYU","ZARUYU","AUDUYU","CADUYU","USDHTG","EURHTG","ZARHTG","AUDHTG","CADHTG","USDPYG","GBPPYG","EURPYG","ZARPYG","AUDPYG","CADPYG","USDISK","GBPISK","EURISK","ZARISK","AUDISK","CADISK","USDNIO","GBPNIO","EURNIO","ZARNIO","AUDNIO","CADNIO","USDZMK","GBPZMK","EURZMK","ZARZMK","AUDZMK","CADZMK","USDBWP","GBPBWP","EURBWP","ZARBWP","AUDBWP","CADBWP","USDAOA","GBPAOA","EURAOA","ZARAOA","AUDAOA","CADAOA","USDRWF","GBPRWF","EURRWF","ZARRWF","AUDRWF","CADRWF","USDBZD","GBPBZD","EURBZD","ZARBZD","AUDBZD","CADBZD","USDMWK","GBPMWK","EURMWK","ZARMWK","AUDMWK","CADMWK","USDMZN","GBPMZN","EURMZN","ZARMZN","AUDMZN","CADMZN","USDXCD","GBPXCD","EURXCD","ZARXCD","AUDXCD","CADXCD","USDLSL","GBPLSL","EURLSL","ZARLSL","AUDLSL","CADLSL","USDPGK","GBPPGK","EURPGK","ZARPGK","AUDPGK","CADPGK","USDSLL","GBPSLL","EURSLL","ZARSLL","AUDSLL","CADSLL","USDSCR","GBPSCR","EURSCR","ZARSCR","AUDSCR","CADSCR","USDDZD","GBPDZD","EURDZD","ZARDZD","AUDDZD","CADDZD","USDTOP","GBPTOP","EURTOP","ZARTOP","AUDTOP","CADTOP","USDVUV","GBPVUV","EURVUV","ZARVUV","AUDVUV","CADVUV","HKDHKD","CHFHKD","HKDNGN","AEDHKD","HKDARS","NZDHKD","HKDAOA","CNYHKD","HKDKRW","MYRHKD","HKDMXN","SGDHKD","HKDVND","TRYHKD","SARHKD","HKDTWD","HKDTHB","NOKHKD","SEKHKD","DKKHKD","HKDRUB","ILSHKD","HKDIDR","HKDKES","HKDLKR","PENHKD","HKDPKR","KWDHKD","HKDKZT","HKDCLP","HKDCZK","HKDCOP","PLNHKD","EGPHKD","HKDPHP","QARHKD","HKDDOP","HKDPYG","OMRHKD","RONHKD","HKDNPR","HKDBDT","HKDJMD","HKDHNL","HKDXAF","JODHKD","HKDMAD","HKDHUF","USDLBP","GBPLBP","AUDLBP","CADLBP","HKDLBP","JPYLBP","EURLBP","AEDAED","AEDAOA","AEDARS","BBDAED","AEDBDT","BGNAED","BHDAED","BRLAED","AEDBWP","BZDAED","CHFAED","AEDCLP","AEDCNY","AEDCOP","AEDCRC","AEDCZK","AEDDKK","AEDDOP","AEDDZD","AEDEGP","FJDAED","GELAED","AEDGHS","AEDGTQ","AEDHNL","AEDHRK","AEDHTG","AEDHUF","AEDIDR","AEDILS","AEDINR","AEDISK","AEDJMD","JODAED","AEDKES","AEDKRW","AEDKWD","AEDKZT","AEDLBP","AEDLKR","AEDLSL","LTLAED","LVLAED","AEDMAD","AEDMNT","AEDMUR","AEDMWK","AEDMXN","AEDMYR","AEDMZN","AEDNGN","AEDNIO","AEDNOK","AEDNPR","NZDAED","OMRAED","PENAED","PGKAED","AEDPHP","AEDPKR","AEDPLN","AEDPYG","AEDQAR","AEDRON","AEDRUB","AEDRWF","AEDSAR","AEDSCR","AEDSEK","SGDAED","AEDSLL","AEDTHB","TNDAED","TOPAED","TRYAED","AEDTWD","AEDUAH","AEDUGX","AEDUYU","AEDVEF","AEDVND","AEDVUV","AEDXAF","XCDAED","AEDXPF","AEDZMK","CNYAOA","CNYARS","BBDCNY","CNYBDT","BGNCNY","BHDCNY","BRLCNY","CNYBWP","BZDCNY","CHFCNY","CNYCLP","CNYCNY","CNYCOP","CNYCRC","CNYCZK","CNYDKK","CNYDOP","CNYDZD","CNYEGP","FJDCNY","GELCNY","GHSCNY","CNYGTQ","CNYHNL","CNYHRK","CNYHTG","CNYHUF","CNYIDR","ILSCNY","CNYINR","CNYISK","CNYJMD","JODCNY","CNYKES","CNYKRW","KWDCNY","CNYKZT","CNYLBP","CNYLKR","CNYLSL","LTLCNY","LVLCNY","CNYMAD","CNYMNT","CNYMUR","CNYMWK","CNYMXN","MYRCNY","CNYMZN","CNYNGN","CNYNIO","CNYNOK","CNYNPR","NZDCNY","OMRCNY","PENCNY","PGKCNY","CNYPHP","CNYPKR","PLNCNY","CNYPYG","QARCNY","RONCNY","CNYRUB","CNYRWF","SARCNY","CNYSCR","CNYSEK","SGDCNY","CNYSLL","CNYTHB","TNDCNY","TOPCNY","TRYCNY","CNYTWD","CNYUAH","CNYUGX","CNYUYU","CNYVEF","CNYVND","CNYVUV","CNYXAF","XCDCNY","CNYXPF","CNYZMK","HKDINR","CHFBBD","CHFBGN","CHFBHD","CHFBRL","CHFBZD","CHFFJD","CHFGEL","CHFJOD","CHFLTL","CHFLVL","CHFNZD","CHFOMR","CHFPEN","CHFPGK","CHFSGD","CHFTND","CHFTOP","CHFTRY","CHFXCD","CHFAOA","CHFARS","CHFBDT","CHFBWP","CHFCLP","CHFCOP","CHFCRC","CHFCZK","CHFDKK","CHFDOP","CHFDZD","CHFEGP","CHFGHS","CHFGTQ","CHFHNL","CHFHRK","CHFHTG","CHFHUF","CHFIDR","CHFILS","CHFINR","CHFISK","CHFJMD","CHFKES","CHFKRW","CHFKWD","CHFKZT","CHFLBP","CHFLKR","CHFLSL","CHFMAD","CHFMNT","CHFMUR","CHFMWK","CHFMXN","CHFMYR","CHFMZN","CHFNGN","CHFNIO","CHFNOK","CHFNPR","CHFPHP","CHFPKR","CHFPLN","CHFPYG","CHFQAR","CHFRON","CHFRUB","CHFRWF","CHFSAR","CHFSCR","CHFSEK","CHFSLL","CHFTHB","CHFTWD","CHFUAH","CHFUGX","CHFUYU","CHFVEF","CHFVND","CHFVUV","CHFXAF","CHFXPF","CHFZMK","CHFCHF","SGDSGD","SGDAOA","SGDARS","SGDBBD","SGDBDT","SGDBGN","SGDBHD","SGDBND","SGDBRL","SGDBWP","SGDBZD","SGDCLP","SGDCOP","SGDCRC","SGDCZK","SGDDKK","SGDDOP","SGDDZD","SGDEGP","SGDFJD","SGDGEL","SGDGHS","SGDGTQ","SGDHNL","SGDHRK","SGDHTG","SGDHUF","SGDIDR","SGDILS","SGDINR","SGDISK","SGDJMD","SGDJOD","SGDKES","SGDKRW","SGDKWD","SGDKZT","SGDLBP","SGDLKR","SGDLSL","SGDLTL","SGDLVL","SGDMAD","SGDMNT","SGDMUR","SGDMWK","SGDMXN","SGDMYR","SGDMZN","SGDNGN","SGDNIO","SGDNOK","SGDNPR","SGDNZD","SGDOMR","SGDPEN","SGDPGK","SGDPHP","SGDPKR","SGDPLN","SGDPYG","SGDQAR","SGDRON","SGDRUB","SGDRWF","SGDSAR","SGDSCR","SGDSEK","SGDSLL","SGDTHB","SGDTND","SGDTOP","SGDTRY","SGDTWD","SGDTZS","SGDUAH","SGDUGX","SGDUYU","SGDVEF","SGDVND","SGDVUV","SGDXAF","SGDXCD","SGDXPF","SGDZMK","MURHKD","JPYVND","GBPHTG","DKKZAR","ZARLBP","USDBND","EURBND","CADBND","GBPBND","AUDBND","CHFBND","AEDBND","CNYBND","HKDBND","JPYBND","HKDBHD","HKDFJD","HKDBRL","ZARBND","USDTZS","EURTZS","CADTZS","GBPTZS","AUDTZS","AEDTZS","CHFTZS","CNYTZS","HKDTZS","JPYTZS","ZARTZS","JPYGHS","JPYCOP","JPYPKR","JPYLKR","JPYBDT","JPYNPR","JPYKZT","JPYJMD","JPYEGP","JPYUGX","JPYCRC","JPYVEF","JPYMNT","JPYCLP","JPYDOP","JPYHNL","JPYXAF","JPYBBD","JPYGEL","JPYUYU","JPYHTG","JPYPYG","JPYISK","JPYNIO","JPYZMK","JPYBWP","JPYAOA","JPYRWF","JPYBZD","JPYMWK","JPYMZN","JPYXCD","JPYLSL","JPYPGK","JPYSLL","JPYSCR","JPYDZD","JPYTOP","JPYVUV","HKDXPF","HKDGTQ","HKDBGN","HKDUAH","HKDLTL","HKDHRK","HKDTND","HKDLVL","HKDGHS","HKDUGX","HKDCRC","HKDVEF","HKDMNT","HKDBBD","HKDGEL","HKDUYU","HKDHTG","HKDISK","HKDNIO","HKDZMK","HKDBWP","HKDRWF","HKDBZD","HKDMWK","HKDMZN","HKDXCD","HKDLSL","HKDPGK","HKDSLL","HKDSCR","HKDDZD","HKDTOP","HKDVUV"]:
       return rate

     else:
       return 1/rate
  $$ LANGUAGE plpythonu;